# Site settings
baseurl = "/"
languageCode = "en-us"
title = "RingoDev"
theme = "freelancer"
disableKinds = ["taxonomyTerm"]

[params]

    images = ["img/profile.png"]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Thomas Grininger's Projects and Ideas"
    description = "My awesome description"

    # Custom assets
	custom_css = ["css/blue_theme.css"]
	custom_js  = []

    [params.head]
    	icon = "logo/favicon.ico"
    	
    [params.navigation]
        brand = "RingoDev"

    [params.header]
    # image should be available in webp and png format
        image = "masthead"
        name = "Thomas Grininger"
        subtitle = "Student - Programmer - Tech-Enthusiast"

    [params.portfolio]
        title = "Portfolio"

        [params.portfolio.modal]
            linkDescription = "Check the Project out on "
            date = "Date"
            category = "Category"
            buttontext = "Close"

    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
	left = "I am a 22 year-old self-taught developer from Austria."
        right = "I am currently doing a bachelors degree in Business & Informatics at the Johannes-Kepler-University in Linz, Austria."

    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"

    [params.footer]
        copyright = "If you find a mistake please open an issue on [GitHub](//github.com/Ringodev/mrhugo)"

        [params.footer.social]
            title = "Around the web"

            [[params.footer.social.networks]]
	    	label = "Github"
                icon = "fa-github"
                link = "//github.com/ringodev"

            [[params.footer.social.networks]]
	    	label = "Xing"
                icon = "fa-xing"
                link = "//xing.com/profile/Thomas_Grininger4"

            [[params.footer.social.networks]]
	    	label = "Twitter"
                icon = "fa-twitter"
                link = "//twitter.com/ringodev1"
